// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using poshtar.Entities;

#nullable disable

namespace poshtar.Entities.Migrations.Mysql
{
    [DbContext(typeof(MysqlDbContext))]
    [Migration("20231111191203_Calendars")]
    partial class Calendars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AddressUser", b =>
                {
                    b.Property<int>("AddressesAddressId")
                        .HasColumnType("int")
                        .HasColumnName("addresses_address_id");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int")
                        .HasColumnName("users_user_id");

                    b.HasKey("AddressesAddressId", "UsersUserId")
                        .HasName("pk_address_user");

                    b.HasIndex("UsersUserId")
                        .HasDatabaseName("ix_address_user_users_user_id");

                    b.ToTable("address_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Disabled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<string>("Expression")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longtext")
                        .HasColumnName("expression")
                        .HasComputedColumnSql("CASE type WHEN 0 THEN pattern WHEN 1 THEN pattern || '%' WHEN 2 THEN '%' || pattern ELSE NULL END", true);

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pattern");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("AddressId")
                        .HasName("pk_addresses");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_addresses_domain_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.HasKey("CalendarId")
                        .HasName("pk_calendars");

                    b.ToTable("calendars", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.CalendarObject", b =>
                {
                    b.Property<int>("CalendarObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calendar_object_id");

                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("FirstOccurence")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_occurence");

                    b.Property<DateTime?>("LastOccurence")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_occurence");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("CalendarObjectId")
                        .HasName("pk_calendar_objects");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_calendar_objects_calendar_id");

                    b.ToTable("calendar_objects", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.CalendarUser", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_write");

                    b.HasKey("CalendarId", "UserId")
                        .HasName("pk_calendar_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_calendar_users_user_id");

                    b.ToTable("calendar_users", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Domain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<DateTime?>("Disabled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("RelayId")
                        .HasColumnType("int")
                        .HasColumnName("relay_id");

                    b.HasKey("DomainId")
                        .HasName("pk_domains");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_domains_name");

                    b.HasIndex("RelayId")
                        .HasDatabaseName("ix_domains_relay_id");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.LogEntry", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_entry_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.HasKey("LogEntryId")
                        .HasName("pk_logs");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_logs_transaction_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<bool>("Delivered")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("delivered");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RecipientId")
                        .HasName("pk_recipients");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_recipients_transaction_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recipients_user_id");

                    b.ToTable("recipients", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Relay", b =>
                {
                    b.Property<int>("RelayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("relay_id");

                    b.Property<DateTime?>("Disabled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("host");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("RelayId")
                        .HasName("pk_relays");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_relays_name");

                    b.ToTable("relays", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Asn")
                        .HasColumnType("longtext")
                        .HasColumnName("asn");

                    b.Property<string>("Client")
                        .HasColumnType("longtext")
                        .HasColumnName("client");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("connection_id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end");

                    b.Property<string>("From")
                        .HasColumnType("longtext")
                        .HasColumnName("from");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("from_user_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Secure")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("secure");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start");

                    b.Property<bool>("Submission")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("submission");

                    b.HasKey("TransactionId")
                        .HasName("pk_transactions");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_transactions_from_user_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("poshtar.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Disabled")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hash");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_master");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<byte[]>("OtpKey")
                        .HasColumnType("longblob")
                        .HasColumnName("otp_key");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int?>("Quota")
                        .HasColumnType("int")
                        .HasColumnName("quota");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("salt");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AddressUser", b =>
                {
                    b.HasOne("poshtar.Entities.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressesAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_user_addresses_addresses_address_id");

                    b.HasOne("poshtar.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_user_users_users_user_id");
                });

            modelBuilder.Entity("poshtar.Entities.Address", b =>
                {
                    b.HasOne("poshtar.Entities.Domain", "Domain")
                        .WithMany("Addresses")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_domains_domain_id");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("poshtar.Entities.CalendarObject", b =>
                {
                    b.HasOne("poshtar.Entities.Calendar", "Calendar")
                        .WithMany("CalendarObjects")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_objects_calendars_calendar_id");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("poshtar.Entities.CalendarUser", b =>
                {
                    b.HasOne("poshtar.Entities.Calendar", "Calendar")
                        .WithMany("CalendarUsers")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_users_calendars_calendar_id");

                    b.HasOne("poshtar.Entities.User", "User")
                        .WithMany("CalendarUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_users_users_user_id");

                    b.Navigation("Calendar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("poshtar.Entities.Domain", b =>
                {
                    b.HasOne("poshtar.Entities.Relay", "Relay")
                        .WithMany("Domains")
                        .HasForeignKey("RelayId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_domains_relays_relay_id");

                    b.Navigation("Relay");
                });

            modelBuilder.Entity("poshtar.Entities.LogEntry", b =>
                {
                    b.HasOne("poshtar.Entities.Transaction", "Transaction")
                        .WithMany("Logs")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logs_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("poshtar.Entities.Recipient", b =>
                {
                    b.HasOne("poshtar.Entities.Transaction", "Transaction")
                        .WithMany("Recipients")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipients_transactions_transaction_id");

                    b.HasOne("poshtar.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_recipients_users_user_id");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("poshtar.Entities.Transaction", b =>
                {
                    b.HasOne("poshtar.Entities.User", "FromUser")
                        .WithMany("Transactions")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("fk_transactions_users_from_user_id");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("poshtar.Entities.Calendar", b =>
                {
                    b.Navigation("CalendarObjects");

                    b.Navigation("CalendarUsers");
                });

            modelBuilder.Entity("poshtar.Entities.Domain", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("poshtar.Entities.Relay", b =>
                {
                    b.Navigation("Domains");
                });

            modelBuilder.Entity("poshtar.Entities.Transaction", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("poshtar.Entities.User", b =>
                {
                    b.Navigation("CalendarUsers");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
